"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import dynamic from "next/dynamic";

const FoodBankMap = dynamic(() => import("./food-bank-map"), { ssr: false });

type User={displayName:string;email:string};
type Context={organizationId:string;organizationName:string;siteId:string;siteName:string;siteRole:string;agentId:string;agentName:string};
type Bank={id:string;name:string;address:string;county:string;state:string;latitude:string;longitude:string;service_radius_miles:string;agent_id:string|null;agent_name:string|null;inventory_units:string};
type Item={id:string;product_name:string;brand:string|null;category:string;subcategory:string|null;quantity:string;unit:string;lot_number:string|null;expiration_date:string|null;warehouse_zone:string|null;bin_location:string|null;condition:string;source_name:string|null;barcode:string|null;notes:string|null;row_version:number};
type Recommendation={type:string;title:string;explanation:string;proposedAction:string;requiresHumanApproval:boolean;evidence:unknown[]};
type View="overview"|"map"|"adjustment"|"inventory"|"agent";

const columns:[keyof Item,string][]=[["product_name","Food item"],["brand","Brand"],["category","Category"],["subcategory","Subcategory"],["quantity","Quantity"],["unit","Unit"],["lot_number","Lot"],["expiration_date","Expiration"],["warehouse_zone","Zone"],["bin_location","Bin"],["condition","Condition"],["source_name","Source"],["barcode","Barcode"],["notes","Notes"]];

async function json(url:string,options?:RequestInit){const response=await fetch(url,options);const body=await response.json();if(!response.ok)throw new Error(body.error||"Request failed");return body;}

export function AtlasDashboard({initialUser}:{initialUser:User|null}){
 const [user,setUser]=useState<User|null>(initialUser);const [view,setView]=useState<View>("overview");const [context,setContext]=useState<Context|null>(null);const [banks,setBanks]=useState<Bank[]>([]);const [items,setItems]=useState<Item[]>([]);const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);const [agent,setAgent]=useState<{summary:Record<string,number>;recommendations:Recommendation[]}|null>(null);
 async function load(){const [b,i]=await Promise.all([json("/api/food-banks"),json("/api/inventory/items")]);setContext(b.context);setBanks(b.foodBanks);setItems(i.items);}
 useEffect(()=>{if(user)load().catch(e=>setNotice(e.message));},[user]);
 if(!user)return <Auth onAuthenticated={u=>setUser(u)}/>;
 const total=items.reduce((n,i)=>n+Number(i.quantity),0),expiring=items.filter(i=>i.expiration_date&&new Date(i.expiration_date).getTime()<Date.now()+7*86400000&&new Date(i.expiration_date).getTime()>=Date.now()).length;
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});location.reload();}
 async function importCsv(file:File){setBusy(true);setNotice("");try{const data=new FormData();data.set("file",file);const result=await json("/api/inventory/import-csv",{method:"POST",body:data});setNotice(`${result.imported} inventory rows imported.`);await load();setView("inventory");}catch(e){setNotice(e instanceof Error?e.message:"Import failed");}finally{setBusy(false);}}
 async function edit(item:Item,field:keyof Item,value:string){if(String(item[field]??"")===value)return;try{const result=await json(`/api/inventory/items/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({field,value:field==="quantity"?Number(value):value||null,rowVersion:item.row_version,reason:"Manual spreadsheet edit"})});setItems(x=>x.map(y=>y.id===item.id?result.item:y));setNotice("Change saved to the shared ledger.");}catch(e){setNotice(e instanceof Error?e.message:"Could not save change");await load();}}
 async function runAgent(){setBusy(true);try{setAgent(await json("/api/agent/monitor"));}catch(e){setNotice(e instanceof Error?e.message:"Agent unavailable");}finally{setBusy(false);}}
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">R</span><div><strong>ReliefLink</strong><small>Food bank operations</small></div></div><div className="site-chip"><small>Your food bank</small><strong>{context?.siteName||"Loading…"}</strong><span><i/> {context?.agentName||"Agent connecting"}</span></div><nav>{([['overview','Overview','⌂'],['map','Food bank map','⌖'],['adjustment','Inventory adjustment','⇧'],['inventory','Inventory spreadsheet','▦'],['agent','Food bank agent','✦']] as [View,string,string][]).map(([id,label,icon])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><span>{icon}</span>{label}</button>)}</nav><div className="sidebar-foot"><strong>{user.displayName}</strong><small>{user.email}</small><button onClick={logout}>Sign out</button></div></aside><main><header className="topbar"><div><p className="eyebrow">{context?.organizationName||"ReliefLink network"}</p><h1>{({overview:"Operations overview",map:"Shared food bank network",adjustment:"Inventory adjustment",inventory:"Inventory spreadsheet",agent:"Food bank agent"} as Record<View,string>)[view]}</h1></div><span className="network-badge"><i/> Shared ledger online</span></header>{notice&&<div className="notice" onClick={()=>setNotice("")}>{notice}<span>×</span></div>}
 {view==="overview"&&<><section className="welcome"><div><p className="eyebrow">Site-scoped workspace</p><h2>Good to see you, {user.displayName.split(" ")[0]}.</h2><p>Your account can update only <strong>{context?.siteName}</strong>. Other registered food banks are visible on the shared network without exposing their item-level ledger.</p></div><button className="button primary" onClick={()=>setView("adjustment")}>Adjust inventory</button></section><section className="metric-row"><Metric label="Inventory rows" value={items.length}/><Metric label="Total units" value={total.toLocaleString()}/><Metric label="Expiring this week" value={expiring}/><Metric label="Registered food banks" value={banks.length}/></section><div className="two-column"><section className="panel"><Header kicker="Shared network" title="Nearby registered food banks"/><div className="bank-list">{banks.slice(0,5).map(b=><div key={b.id}><span className="bank-icon">⌂</span><div><strong>{b.name}</strong><small>{b.address}, {b.county} County</small></div><b>{Number(b.inventory_units).toLocaleString()} units</b></div>)}</div><button className="text-button" onClick={()=>setView("map")}>Open network map →</button></section><section className="panel"><Header kicker="Your agent" title={context?.agentName||"Food bank agent"}/><p className="muted">Monitors expiration dates, low stock, and missing warehouse locations. It explains recommendations and asks permission before any operational commitment.</p><div className="authority"><strong>Human authority enforced</strong><span>The agent cannot order, transfer, reserve, or dispose of inventory on its own.</span></div><button className="button primary full" onClick={()=>{setView("agent");void runAgent();}}>Review agent findings</button></section></div></>}
 {view==="map"&&<section className="panel map-panel"><Header kicker="Network visibility" title={`${banks.length} registered food banks`}/><p className="muted">Only food banks registered by an account administrator appear here. Select a marker to view its public operating profile and agent status.</p><FoodBankMap foodBanks={banks}/></section>}
 {view==="adjustment"&&<section className="panel import-panel"><Header kicker="CSV intake" title="Add inventory to the shared ledger"/><div className="import-grid"><div className="drop-card"><span className="upload-icon">⇧</span><h3>Import a CSV file</h3><p>Use one row per food item or lot. You can correct every value in the spreadsheet after import.</p><label className="button primary">{busy?"Importing…":"Choose CSV file"}<input type="file" accept=".csv,text/csv" disabled={busy} onChange={e=>e.target.files?.[0]&&void importCsv(e.target.files[0])}/></label></div><div><h3>Required columns</h3><div className="column-tags"><span>product_name</span><span>category</span><span>quantity</span><span>unit</span></div><h3>Optional properties</h3><p className="muted">brand, subcategory, lot_number, expiration_date, warehouse_zone, bin_location, condition, source_name, barcode, notes</p><a className="text-button" href={'data:text/csv;charset=utf-8,'+encodeURIComponent('product_name,brand,category,subcategory,quantity,unit,lot_number,expiration_date,warehouse_zone,bin_location,condition,source_name,barcode,notes\nCanned corn,Green Farm,Vegetables,Canned,24,cans,LOT-101,2027-04-15,A,12,good,Community donation,012345678901,')} download="relieflink-inventory-template.csv">Download CSV template ↓</a></div></div><div className="scope-note"><strong>Scoped to {context?.siteName}</strong><span>This import cannot alter another food bank&apos;s inventory.</span></div></section>}
 {view==="inventory"&&<section className="panel sheet-panel"><div className="sheet-head"><Header kicker="Live shared ledger" title={`${items.length} inventory records`}/><button className="button secondary" onClick={()=>setView("adjustment")}>Import CSV</button></div><p className="muted">Click any cell, make a change, then press Enter or click away. Every edit is saved immediately and audit logged.</p><div className="sheet-wrap"><table><thead><tr>{columns.map(([f,l])=><th key={f}>{l}</th>)}</tr></thead><tbody>{items.length?items.map(item=><tr key={item.id}>{columns.map(([field])=><td key={field}><input type={field==="quantity"?"number":field==="expiration_date"?"date":"text"} defaultValue={field==="expiration_date"&&item[field]?String(item[field]).slice(0,10):String(item[field]??"")} onKeyDown={e=>{if(e.key==="Enter")e.currentTarget.blur();}} onBlur={e=>void edit(item,field,e.target.value)}/></td>)}</tr>):<tr><td colSpan={columns.length} className="empty">No inventory yet. Import a CSV to begin.</td></tr>}</tbody></table></div></section>}
 {view==="agent"&&<section><div className="agent-hero"><div><span className="agent-orb">✦</span><div><p className="eyebrow">Site agent</p><h2>{context?.agentName}</h2><p>Observes only {context?.siteName}&apos;s ledger and presents explainable recommendations for human review.</p></div></div><button className="button light" disabled={busy} onClick={()=>void runAgent()}>{busy?"Reviewing ledger…":"Run inventory review"}</button></div>{agent&&<><section className="metric-row"><Metric label="Items monitored" value={agent.summary.items}/><Metric label="Total units" value={agent.summary.totalUnits}/><Metric label="Expiring soon" value={agent.summary.expiring}/><Metric label="Missing locations" value={agent.summary.missingLocations}/></section><div className="recommendations">{agent.recommendations.length?agent.recommendations.map((r,i)=><article className="panel" key={r.type}><span className="rec-number">0{i+1}</span><div><p className="eyebrow">Recommendation · approval required</p><h3>{r.title}</h3><p>{r.explanation}</p><div className="proposed"><small>Proposed next step</small><strong>{r.proposedAction}</strong></div><button className="button secondary" onClick={()=>setNotice("Review acknowledged. No inventory or external commitment was changed.")}>Acknowledge for human review</button></div></article>):<div className="panel empty-state"><h3>No issues detected</h3><p>The current inventory does not trigger expiration, low-stock, or location completeness alerts.</p></div>}</div></>}</section>}
 </main></div>;
}

function Metric({label,value}:{label:string;value:string|number}){return <div className="metric"><small>{label}</small><strong>{value}</strong></div>}
function Header({kicker,title}:{kicker:string;title:string}){return <div className="section-heading"><div><p className="eyebrow">{kicker}</p><h2>{title}</h2></div></div>}
function Auth({onAuthenticated}:{onAuthenticated:(user:User)=>void}){const [mode,setMode]=useState<'login'|'register'>('login'),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);const payload=Object.fromEntries(form);try{const body=await json(mode==='login'?'/api/auth/login':'/api/auth/register-food-bank',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});onAuthenticated(body.user);}catch(x){setError(x instanceof Error?x.message:'Unable to continue');}finally{setBusy(false)}}return <main className="auth-shell"><section className="auth-story"><div className="brand large"><span className="brand-mark">R</span><div><strong>ReliefLink</strong><small>Shared food bank operations</small></div></div><div><p className="eyebrow">One network. Local control.</p><h1>Coordinate inventory without giving up human authority.</h1><p>Each registered food bank gets a private, site-scoped ledger and its own monitoring agent—while the network map makes nearby partners visible.</p></div><div className="auth-points"><span>✓ Shared Postgres ledger</span><span>✓ Editable inventory spreadsheet</span><span>✓ Human-governed agents</span></div></section><section className="auth-card"><div className="auth-tabs"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Sign in</button><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Register a food bank</button></div><form onSubmit={submit}><h2>{mode==='login'?'Welcome back':'Join the ReliefLink network'}</h2><p>{mode==='login'?'Access your food bank workspace.':'Creates the food bank, administrator account, shared-map listing, and site agent.'}</p>{mode==='register'&&<><label>Food bank name<input name="foodBankName" required/></label><label>Street address<input name="address" required/></label><div className="form-row"><label>County<input name="county" required/></label><label>State<input name="state" defaultValue="CA" maxLength={2} required/></label></div><div className="form-row"><label>Latitude<input name="latitude" type="number" step="any" required/></label><label>Longitude<input name="longitude" type="number" step="any" required/></label></div><label>Your name<input name="displayName" required/></label></>}<label>Email<input name="email" type="email" required/></label><label>Password<input name="password" type="password" minLength={mode==='register'?12:8} required/></label>{error&&<div className="form-error">{error}</div>}<button className="button primary full" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Register food bank'}</button></form></section></main>}
